apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken
  namespace: class
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken
  template:
    metadata:
      labels:
        app: broken
    spec:
      containers:
        - name: broken
          image: nginx:this-tag-does-not-exist
